models.py
from flask_sqlalchemy import SQLAlchemy
from werkzeug.security import generate_password_hash, check_password_hash
from flask_jwt_extended import JWTManager
import os
import rsa

db = SQLAlchemy()
jwt = JWTManager()

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    country = db.Column(db.String(20), unique=True, nullable=False)
    comission = db.Column(db.Integer, nullable=False)
    password_hash = db.Column(db.String(80), nullable=False)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

def encrypt_password(password):
    private_key = os.environ['PRIVATE_KEY'].encode()
    encrypted_data = rsa.encrypt(password.encode(), public_key=private_key)
    return encrypted_data.hex()

def decrypt_password(encrypted_password):
    decrypted_data = bytes.fromhex(encrypted_password)
    decrypted_text = rsa.decrypt(decrypted_data, private_key=os.environ['PRIVATE_KEY'].encode()).decode()
    return decrypted_text

def create_user(country, password):
    user = User(country=country)
    user.set_password(password)
    db.session.add(user)
    db.session.commit()
    return user

def get_user_by_country(country):
    return User.query.filter_by(country=country).first()

app.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_jwt_extended import JWTManager
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.backends import default_backend
import os, config, models
from cryptography.hazmat.primitives.asymmetric import rsa
from routes import bp


script_dir = os.path.dirname(os.path.abspath(__file__))
template_dir = os.path.join(script_dir, 'templates')

if not os.path.exists(template_dir):
    print("Error: El directorio de templates no existe.")

def create_app():
    app = Flask(__name__, template_folder=template_dir)
    
    app.config.from_object(config.Config)
    app.register_blueprint(bp)
    models.db.init_app(app)
    models.jwt.init_app(app)

    with app.app_context():
        models.db.create_all()

    return app

# Generar claves RSA
private_key = rsa.generate_private_key(
    public_exponent=65537,
    key_size=2048,
    backend=default_backend()
)

public_key = private_key.public_key()

# Guardar la clave privada encriptada
encrypted_private_key = private_key.private_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PrivateFormat.PKCS8,
    encryption_algorithm=serialization.NoEncryption()
)

# Guardar la clave pública
public_pem = public_key.public_bytes(
    encoding=serialization.Encoding.PEM,
    format=serialization.PublicFormat.SubjectPublicKeyInfo
)

# Guardar las claves en archivos seguros
with open("private_key.pem", "wb") as f:
    f.write(encrypted_private_key)

with open("public_key.pem", "wb") as f:
    f.write(public_pem)


if __name__ == '__main__':
    app = create_app()
    with app.app_context():
        app.run(debug=True, port=4000)

routes.py
from flask import Flask, request, jsonify, render_template, Blueprint
from flask_jwt_extended import JWTManager, create_access_token, jwt_required, get_jwt_identity
import models

bp = Blueprint('main', __name__)

# Rutas
@bp.route('/')
def home():
    return render_template('index.html')

@bp.route('/edition')
def edition():
    return render_template('edition.html')

@bp.route('/our Team')
def our_team():
    return render_template('ourteam.html')

@bp.route('/history')
def history():
    return render_template('history.html')

@bp.route('/academic_design')
def academic_design():
    return render_template('academicdesign.html')

@bp.route('/take_part')
def take_part():
    return render_template('takepart.html')

@bp.route('/votation_system')
def votation_system():
    return render_template('login.html')

@bp.route('/contact_us')
def contact_us():
    return render_template('contact.html')

@bp.route('/resources')
def resources():
    return render_template('resources.html')

@bp.route('/comision1')
def comision1():
    return render_template('comision1.html')

@bp.route('/comision2')
def comision2():
    return render_template('comision2.html')

@bp.route('/comision3')
def comision3():
    return render_template('comision3.html')

@bp.route('/comision4')
def comision4():
    return render_template('comision4.html')

@bp.route('/comision5')
def comision5():
    return render_template('comision5.html')

@bp.route('/api/check_credentials', methods=["GET", "POST"])
def process_form():
    if request.method == "POST":
        
        country = request.form.get("country")
        comission = request.form.get("commission")
        password = request.form.get("password")

        print('Recivied Data:', country, comission, password)

        user = models.get_user_by_country(country)

        if not user:
            return jsonify({"msg": "El usuario no existe"}), 400
        if not user.check_password(password):
            return jsonify({"msg": "Contraseña incorrecta"}), 401
        
        access_token = create_access_token(identity=country)
        return render_template('acceptance.html', access_token=access_token)

    return render_template('loging.html')


@bp.route('/acceptance.html')
@jwt_required()
def acceptance():
    current_user = get_jwt_identity()
    return render_template('acceptance.html', current_user=current_user)

templates/acceptance.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}">
    <title>Conclusions</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/acceptance.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/generalstyle.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900" rel="stylesheet">
</head>
<body>
    <input type="checkbox" id="toggle-nav" class="toggle-checkbox">
    <label for="toggle-nav" class="toggle-btn">
        <img src="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}" alt="Menú">
    </label>
    <nav class="navegation-bar">
        <ul> 
            <li><a href="{{ url_for('main.home') }}">INICIO</a></li>
            <li><a href="{{ url_for('main.edition') }}">EDICIÓN XXVIII</a></li>
            <li><a href="{{ url_for('main.our_team') }}">NUESTRO EQUIPO</a></li>
            <li><a href="{{ url_for('main.history') }}">HISTORIA DEL MODELO</a></li>
            <li><a href="{{ url_for('main.academic_design') }}">DISEÑO ACADÉMICO</a></li>
            <li><a href="{{ url_for('main.take_part') }}">CÓMO PARTICIPAR</a></li>
            <li><a href="{{ url_for('main.votation_system') }}">SISTEMA DE VOTACIÓN</a></li>
            <li><a href="{{ url_for('main.contact_us') }}">CONTÁCTANOS</a></li>
            <li><a href="{{ url_for('main.resources') }}">RECURSOS ACADÉMICOS</a></li>
        </ul>
    </nav>


    <div class="content">
        <div class = "card">   
            <p>Quorum:</p>
            <p>Presentes:</p>
            <p>A Favor:</p>
            <p>En Contra:</p>
            <p>Porcentaje:</p>
        </div>
    </div>
</body>
</html>

templates/comision2.html
<!DOCTYPE html>
<html> 
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}">
    <title>Havmun</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/comision2.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/generalstyle.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900" rel="stylesheet">
</head>
<body>
    <input type="checkbox" id="toggle-nav" class="toggle-checkbox">
    <label for="toggle-nav" class="toggle-btn">
        <img src="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}" alt="Menú">
    </label>
    <nav class="navegation-bar">
        <ul> 
            <li><a href="{{ url_for('main.home') }}">INICIO</a></li>
            <li><a href="{{ url_for('main.edition') }}">EDICIÓN XXVIII</a></li>
            <li><a href="{{ url_for('main.our_team') }}">NUESTRO EQUIPO</a></li>
            <li><a href="{{ url_for('main.history') }}">HISTORIA DEL MODELO</a></li>
            <li><a href="{{ url_for('main.academic_design') }}">DISEÑO ACADÉMICO</a></li>
            <li><a href="{{ url_for('main.take_part') }}">CÓMO PARTICIPAR</a></li>
            <li><a href="{{ url_for('main.votation_system') }}">SISTEMA DE VOTACIÓN</a></li>
            <li><a href="{{ url_for('main.contact_us') }}">CONTÁCTANOS</a></li>
            <li><a href="{{ url_for('main.resources') }}">RECURSOS ACADÉMICOS</a></li>
            

        </ul>
    </nav>

    <div class="content">
        <h1>Noticias y documentos de interés</h1>
        <ul class="commissions">
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/A_RES_43_53-EN.pdf') }}" download="A/RES/43/53"> A/RES/43/53</a></li>  
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/A_RES_64_73-EN.pdf') }}" download="A/RES/64/73">A/RES/74/73 </a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/A_RES_65_159-EN.pdf') }}" download="A/RES/65/159">A/RES/65/159</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/A_RES_66_200-EN.pdf') }}" download="A/RES/66/200">A/RES/66/200</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/A_RES_68_212-EN.pdf') }}" download="A/RES/68/212">A/RES/68/212</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/A_RES_69_220-EN.pdf') }}" download="A/RES/69/220">A/RES/69/220</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/A_RES_70_205-EN.pdf') }}" download="A/RES/70/205">A/RES/70/205</a></li>
            
        </ul>

templates/comision3.html
<!DOCTYPE html>
<html> 
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}">
    <title>Havmun</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/comision3.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/generalstyle.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900" rel="stylesheet">
</head>
<body>
    <input type="checkbox" id="toggle-nav" class="toggle-checkbox">
    <label for="toggle-nav" class="toggle-btn">
        <img src="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}" alt="Menú">
    </label>
    <nav class="navegation-bar">
        <ul> 
            <li><a href="{{ url_for('main.home') }}">INICIO</a></li>
            <li><a href="{{ url_for('main.edition') }}">EDICIÓN XXVIII</a></li>
            <li><a href="{{ url_for('main.our_team') }}">NUESTRO EQUIPO</a></li>
            <li><a href="{{ url_for('main.history') }}">HISTORIA DEL MODELO</a></li>
            <li><a href="{{ url_for('main.academic_design') }}">DISEÑO ACADÉMICO</a></li>
            <li><a href="{{ url_for('main.take_part') }}">CÓMO PARTICIPAR</a></li>
            <li><a href="{{ url_for('main.votation_system') }}">SISTEMA DE VOTACIÓN</a></li>
            <li><a href="{{ url_for('main.contact_us') }}">CONTÁCTANOS</a></li>
            <li><a href="{{ url_for('main.resources') }}">RECURSOS ACADÉMICOS</a></li>
            

        </ul>
    </nav>

    <div class="content">
        <h1>Noticias y documentos de interés</h1>
        <ul class="commissions">
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/A_62_126_ES.pdf') }}"download="A/RES/62/126"> A/RES/62/126</a></li>  
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/A_76_463-EN.pdf') }}" download="A/RES/76/463">A/RES/76/463 </a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/A_76_PV.53-EN.pdf') }}" download="A/RES/PV.53">A/RES/PV.53</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/A_C.3_76_L.6-EN.pdf') }}" download="A/RES/C.3/76/L.6">A/RES/C.3/76/L.6</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/A_RES_63_195_ES.pdf') }}" download="A/RES/63/195">A/RES/63/195</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/Declaracion_de_Lima_VCumbreALC-UE_2008.pdf') }}" download="Declaracion_de_Lima_VCumbreALC-UE_2008">Declaración de Lima en Quinta Cumbre América Latina y Caribe– Unión Europea</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/Noticias.docx') }}" download="Noticias">Noticias</a></li>
            
        </ul>

templates/comision4.html
<!DOCTYPE html>
<html> 
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}">
    <title>Havmun</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/comision4.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/generalstyle.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900" rel="stylesheet">
</head>
<body>
    <input type="checkbox" id="toggle-nav" class="toggle-checkbox">
    <label for="toggle-nav" class="toggle-btn">
        <img src="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}" alt="Menú">
    </label>
    <nav class="navegation-bar">
        <ul> 
            <li><a href="{{ url_for('main.home') }}">INICIO</a></li>
            <li><a href="{{ url_for('main.edition') }}">EDICIÓN XXVIII</a></li>
            <li><a href="{{ url_for('main.our_team') }}">NUESTRO EQUIPO</a></li>
            <li><a href="{{ url_for('main.history') }}">HISTORIA DEL MODELO</a></li>
            <li><a href="{{ url_for('main.academic_design') }}">DISEÑO ACADÉMICO</a></li>
            <li><a href="{{ url_for('main.take_part') }}">CÓMO PARTICIPAR</a></li>
            <li><a href="{{ url_for('main.votation_system') }}">SISTEMA DE VOTACIÓN</a></li>
            <li><a href="{{ url_for('main.contact_us') }}">CONTÁCTANOS</a></li>
            <li><a href="{{ url_for('main.resources') }}">RECURSOS ACADÉMICOS</a></li>
            

        </ul>
    </nav>

    <div class="content">
        <h1>Noticias y documentos de interés</h1>
        <ul class="commissions">
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/DERECHO NUCLEAR- DEBATE MUNDIAL.pdf') }}"download="Derecho Nuclear"> Derecho Nuclear-Debate Mundial</a></li>  
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/Examen periódico de las centrales nucleares.pdf') }}" download="Examen periódico de las centrales nucleares">Examen periódico de las centrales nucleares </a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/INFORME ANUAL DEL OIEA DE 2022.pdf') }}" download="INFORME ANUAL DEL OIEA DE 2022">Informe Anual de OIEA(2022)</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/LA LABOR DEL COMITÉ CIENTÍFICO DE LAS NACIONES UNIDAS.pdf') }}" download="LA LABOR DEL COMITÉ CIENTÍFICO DE LAS NACIONES UNIDAS">Labor del Comité Científico de las Naciones Unidas</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/Manual para las delegaciones 78 AGNU.pdf') }}" download="Manual para las delegaciones 78 AGNU">Manual para las delegaciones.Sesión 78 AGNU</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/Nuclear Safety and Security.pdf') }}" download="Nuclear Safety and Security">Nuclear Safety and Security</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/Protección radiológica y seguridad de las fuentes de radiación- Normas básicas internacionales de seguridad.pdf') }}" download="Protección radiológica y seguridad de las fuentes de radiación- Normas básicas internacionales de seguridad">Protección radiológica y seguridad de las fuentes de radiación</a></li>
            
        </ul>

templates/comision5.html
<!DOCTYPE html>
<html> 
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}">
    <title>Havmun</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/comision5.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/generalstyle.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900" rel="stylesheet">
</head>
<body>
    <input type="checkbox" id="toggle-nav" class="toggle-checkbox">
    <label for="toggle-nav" class="toggle-btn">
        <img src="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}" alt="Menú">
    </label>
    <nav class="navegation-bar">
        <ul> 
            <li><a href="{{ url_for('main.home') }}">INICIO</a></li>
            <li><a href="{{ url_for('main.edition') }}">EDICIÓN XXVIII</a></li>
            <li><a href="{{ url_for('main.our_team') }}">NUESTRO EQUIPO</a></li>
            <li><a href="{{ url_for('main.history') }}">HISTORIA DEL MODELO</a></li>
            <li><a href="{{ url_for('main.academic_design') }}">DISEÑO ACADÉMICO</a></li>
            <li><a href="{{ url_for('main.take_part') }}">CÓMO PARTICIPAR</a></li>
            <li><a href="{{ url_for('main.votation_system') }}">SISTEMA DE VOTACIÓN</a></li>
            <li><a href="{{ url_for('main.contact_us') }}">CONTÁCTANOS</a></li>
            <li><a href="{{ url_for('main.resources') }}">RECURSOS ACADÉMICOS</a></li>
            

        </ul>
    </nav>

    <div class="content">
        <h1>Noticias y documentos de interés</h1>
        <ul class="commissions">
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/n0432844.pdf') }}"download="S/RES/1540 (2004)"> S/RES/1540 (2004)</a></li>  
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/n0633111.pdf') }}" download="S/RES/1673">S/RES/74/73 </a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/n1130680.pdf') }}" download="S/RES/1977 (2011)">S/RES/1977 (2011)</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/n1348924.pdf') }}" download="S/RES/2118 (2013)">S/RES/2118 (2013)</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/1976_enmod.pdf') }}" download="Convention de 1976 sur l'interdiction d'utiliser des techniques de modification de l'environnement">Convention de 1976 sur l'interdiction d'utiliser des techniques de modification de l'environnement</a></li>
            <li><a href="{{ url_for('static', filename='pdfs/Comissions/S0035336100050383a.pdf') }}" download="La Convention sur les armes biologiques">La Convention sur les armes biologiques</a></li>
          
        </ul>

templates/contact.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}">
    <title>Havmun</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/contact.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/generalstyle.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900" rel="stylesheet">
</head>
<body>
    <input type="checkbox" id="toggle-nav" class="toggle-checkbox">
    <label for="toggle-nav" class="toggle-btn">
        <img src="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}" alt="Menú">
    </label>
    <nav class="navegation-bar">
        <ul> 
            <li><a href="{{ url_for('main.home') }}">INICIO</a></li>
            <li><a href="{{ url_for('main.edition') }}">EDICIÓN XXVIII</a></li>
            <li><a href="{{ url_for('main.our_team') }}">NUESTRO EQUIPO</a></li>
            <li><a href="{{ url_for('main.history') }}">HISTORIA DEL MODELO</a></li>
            <li><a href="{{ url_for('main.academic_design') }}">DISEÑO ACADÉMICO</a></li>
            <li><a href="{{ url_for('main.take_part') }}">CÓMO PARTICIPAR</a></li>
            <li><a href="{{ url_for('main.votation_system') }}">SISTEMA DE VOTACIÓN</a></li>
            <li><a href="{{ url_for('main.contact_us') }}">CONTÁCTANOS</a></li>
            <li><a href="{{ url_for('main.resources') }}">RECURSOS ACADÉMICOS</a></li>
        </ul>
    </nav>

    <div class="content">
    <h1>Contáctanos</h1>
    
    <p>Via email</p>
    <a href="mailto:havmun.evento@uh.cu" target="_blank">havmun.evento@uh.cu</a>
    <a href="mailto:academico.havmun@gmail.com" target="_blank">academico.havmun@gmail.com</a>
    
    <p>Via Instagram</p>
    <a href="https://www.instagram.com/havmun?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw== " target="_blank">Havmun</a>

    <img src="{{ url_for('static', filename='img/contact interf.JPG') }}" alt="">
    </div>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}">
    <title>Sistema de Votación</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/login.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/generalstyle.css') }}">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900" rel="stylesheet">
</head>
<body>
    <input type="checkbox" id="toggle-nav" class="toggle-checkbox">
    <label for="toggle-nav" class="toggle-btn">
        <img src="{{ url_for('static', filename='img/HAVMUN-transformed.png') }}" alt="Menú">
    </label>
    <nav class="navegation-bar">
        <ul> 
            <li><a href="{{ url_for('main.home') }}">INICIO</a></li>
            <li><a href="{{ url_for('main.edition') }}">EDICIÓN XXVIII</a></li>
            <li><a href="{{ url_for('main.our_team') }}">NUESTRO EQUIPO</a></li>
            <li><a href="{{ url_for('main.history') }}">HISTORIA DEL MODELO</a></li>
            <li><a href="{{ url_for('main.academic_design') }}">DISEÑO ACADÉMICO</a></li>
            <li><a href="{{ url_for('main.take_part') }}">CÓMO PARTICIPAR</a></li>
            <li><a href="{{ url_for('main.votation_system') }}">SISTEMA DE VOTACIÓN</a></li>
            <li><a href="{{ url_for('main.contact_us') }}">CONTÁCTANOS</a></li>
            <li><a href="{{ url_for('main.resources') }}">RECURSOS ACADÉMICOS</a></li>
        </ul>
    </nav>

    <div class="content">
        <h1>Inicio de sesión</h1>

        <div class="registration">
            <form action="{{ url_for('main.process_form') }}" method="POST" class="form-register">
                <div class="form-group">
                    <h4 class="subtitle">País</h4>
                    <input type="text" name="country" required>
                </div>

                <div class="form-group">
                    <h4 class="subtitle">Comisión</h4>
                    <input type="text" name="commission" required>
                </div>

                <div class="form-group">
                    <h4 class="subtitle">Contraseña</h4>
                    <input type="password" name="password" required>
                </div>
                <br>
                <br>
                <button type="submit">Registrarse</button>
            </form>
        </div>
    </div>

</body>
</html>